# Generated by Django 4.1.2 on 2023-04-16 14:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_auto_20230204_1451"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="stripe_id",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
